skins.2=2
name.2=Thatoneguyjames
skins.3=3
name.3=Dadmann
skins.4=4
name.4=alex
skins.5=5
name.5=ari
skins.6=6
name.6=efe
skins.7=7
name.7=kai
skins.8=8
name.8=makena
skins.9=9
name.9=noor
skins.10=10
name.10=zuri
skins.11=11
name.11=sunny