models.1=2
name.1=regex:^Donald Duck$
models.2=2
name.2=regex:^Scrooge McDuck$
models.3=2
name.3=regex:^Daisy Duck$
models.4=2
name.4=regex:^Huey Duck$
models.5=2
name.5=regex:^Dewey Duck$
models.6=2
name.6=regex:^Louie Duck$
models.7=3
name.7=regex:^Psyduck$
models.8=4
name.8=regex:^Daffy Duck$
models.9=5
name.9=regex:^Duck$