models.1=2
nbt.1.equipment.chest.components.minecraft\:custom_name=Ruinbound Carrier
names.1=SHO310

models.2=3
nbt.2.equipment.chest.components.minecraft\:custom_name=Runic Sheath
nbt.2.SelectedItem.id=minecraft:diamond_sword
names.2=SHO310

models.3=4
nbt.3.equipment.chest.components.minecraft\:custom_name=Runic Sheath
names.3=SHO310