name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Make new build
      run: make build

    - name: Deploy release
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: release
        FOLDER: releases/final
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  notify_new_release:
    needs: build-and-release
    runs-on: ubuntu-latest
  
    steps:
      - name: Notify on Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\"<@&1304940615036960828> A new release of the custom models has been created! Please log in to the [Admin Console](https://panel.wabbanode.com/server/90969b73-4292-43ec-9c91-528339ee10cf) and run the \`/fetchhash\` command to update to the latest resource pack!\"}" \
               "$WEBHOOK_URL"
